### ISSUE TITLE
  @in partnersforroles::Dict{Integer,Integer} will not trigger @onchange

### ISSUE THREAD

**Issue by michaelfliegner** [GenieFramework/Stipple.jl#169]
... while `@in partnersforroles::Dict{String,Integer}` does

This is relevant for example for dynamic html fragments for input of multiple ids, one for each of a predetermined set of roles. In my case partners for contracts in different roles.

Minimal NOT working example:

[mnwe.zip](https://github.com/GenieFramework/Stipple.jl/files/10558219/mnwe.zip)

But you can rescue the example changing the dict´s type.

**Comment by hhaensel** [comment]
That's a very interesting question. It has to do with the fact that we always read JSON into `Dict{String, Any}`.

In principle JSON3 offers nicer parsing than we currently use. It would be a larger refactoring to change this, but it came up very recently in a discussion in the core team.
Meanwhile, you can work around the problem by defining
```julia
Stipple.stipple_parse(::Type{Dict{N, T}}, value::Dict) where {T, N<:Number} = Dict( zip(Vector{N}(parse.(Float64, keys(value))), Vector{T}(collect(values(value)))) )
```
Note that I parsed into `Float64` first and then typecasted in order to offer a general solution which would work with more than Integer types. You could, of course, use `Int` instead of `Float64`.

@essenciary we should probably introduce this definition into Stipple?

**Comment by hhaensel** [comment]
My final Stipple implementation would read
```julia

function stipple_parse(::Type{Dict{N, T}}, value::Dict{String, <:Any}) where {T, N<:Number}
  Dict( zip(Vector{N}(stipple_parse(Vector{N}, collect(keys(value)))), stipple_parse(Vector{T}, collect(values(value)))) )
end

function stipple_parse(::Type{Integer}, value::String)
  stipple_parse(Int, value)
end

function stipple_parse(::Type{AbstractFloat}, value::String)
  stipple_parse(Float64, value)
end
```

**Comment by hhaensel** [comment]
I generalized above solution by releasing `N<:Number` and implemented it in Stipple.
Furthermore, I merged the pending PR #159 which allows you to write `@push` instead of `push!(__model_)`

A new version has just been released, please try and feedback.

**Comment by michaelfliegner** [comment]
> to

🥰

**Comment by PGimenez** [comment]
@michaelfliegner has this issue been resolved?

**Comment by michaelfliegner** [comment]
Sorry, don't know. I gave up on Julia programming.

**Comment by PGimenez** [comment]
That's too bad :( I'm closing this then.
