### ISSUE TITLE
change btn text

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/Stipple.jl#170]
i wanna build a button with a text like counter : 0
i click on the button and it should be counter : 1, then counter: 2, etc
i tried several ways but none of them worked
btn("counter : {{count}}", @click("count += 1"))
or 
btn("counter : {{count}}", @text("count"), @click("count += 1")) ===> it'll be 0, 1, 2, 3, 4 ..., without counter :, just the number

**Comment by hhaensel** [comment]
Currently only on my mobile, try
```
btn(R"'counter: ' + count", @click("count += 1"))
```

**Comment by hhaensel** [comment]
Or maybe `+ this.count`

**Comment by alerem18** [comment]
didn't work

**Comment by hhaensel** [comment]
I'll post something tonight, cannot be too difficult

**Comment by alerem18** [comment]
still doesn't work

**Comment by hhaensel** [comment]
Definitely needs to be changed in StippleUI.
But this now does work:
```julia
@app begin
    @in! count = 0
end

ui() = [
    quasar(:btn, "", label = R"'count: ' + count", color = "primary", @click("count += 1"))
]

p = @page("/", ui)

up()
```

**Comment by alerem18** [comment]
thanks it's working, i wonder what's difference between the first string("") and label in button
why do we need to have a button like this? btn( A string, label=...)

anyway it's working as expected thanks

**Comment by hhaensel** [comment]
Fixed it in StippleUI#master. Then you can do `btn(R"'counter: ' + count", color = "primary", @click("count += 1"))`


@AbhimanyuAryan should we release a new version?

**Comment by hhaensel** [comment]
> thanks it's working, i wonder what's difference between the first string("") and label in button why do we need to have a button like this? btn( A string, label=...)
> 
> anyway it's working as expected thanks

It's not yet well documented, but the general syntax of UI elements is:
- the first positional argument is passed as content to the element
- any following non-array argument is passed as parameter to the element
- any array is joined and passed as content
- if an element does not support content, e.g. `q-btn`, then the first argument is passed as parameter.
- keyword arguments are passed pretty much the same as the Julia expression, except that
    - `__` is converted to `-`
    - `!` in the middle of a keyword is converted to `.`
    - `!` at the end of a keyword indicates that the argument should be treated as js expression
    - a Symbol as value of a keyword argument indicates that the argument should be treated as js expression

But why do we need the `""` then?
Some characters cannot be used in keywords, particularly `@` which is often used in Quasar's syntax. Therefore we use macros to work around that probalem. But as macros cannot generate keyword arguments, we generate an expression that must be passed as parameter. So in order to not end up as content when they are passed as first positional argument, we need to pass an empty first positional argument.
It's not very nice, but that's how it currently is.

There's one other way around, which we learned only recently; any string sequence can be passed as keyword argument if it is bracketet by `var"<string sequence>"`. So you could also write your button like `btn(R"'counter: ' + count", var"@click" = "count += 1")`.

The function `quasar()` can be used to generate any quasar element which is not yet supported by StippleUI. In an analogous way we have `vue()` to pace generic vue elements and `xelem()` to generate any html element.

Finally we have the string macro `R_str` to convert a string to a symbol, e.g. `R"this is a Symbol with space characters"`
I hope that makes things clearer.
Try it out at the REPL to get a better understanding.

**Comment by hhaensel** [comment]
Answering your question I had a new idea to generate keyword arguments.

@essenciary , @AbhimanyuAryan 

if we'd define
```julia
macro click(expr)
    Expr(:kw, R"@click", expr)
end
```
everything works just fine even without a preceding `""`
What do you think?
