### ISSUE TITLE
[Help] How to draw a image (xx.jpg) on canvas ?

### ISSUE THREAD

**Issue by touchft** [GenieFramework/Stipple.jl#18]
Stipple is great tool for me to display data on the web !  I need a bit of help to dynamically display a image on the canvas. The following is my situation:

I have a serial of images (from some video) to be processed and I want to the processed image to be displayed on the canvas automatically if I bind the something to the image variable.

A similar situation used in Dash example is  [here!](https://dash-gallery.plotly.host/dash-object-detection/)

Could you give me some light how to solve my problem?  

Thank you.

**Comment by essenciary** [comment]
@touchft Thanks for the details, this looks like a great use case for Stipple indeed. As @hhaensel mentioned in the other issue, we need to add an image wrapper to Stipple. I'll take a look at this, I'll try to squeeze it into my schedule this week. Please do keep us in the loop re your progress, eg if you're trying the implementation described by @hhaensel

**Comment by essenciary** [comment]
Looking at the Dash demo, would you show the images instead of the youtube video?

**Comment by hhaensel** [comment]
> @touchft Thanks for the details, this looks like a great use case for Stipple indeed. As @hhaensel mentioned in the other issue, we need to add an image wrapper to Stipple. I'll take a look at this, I'll try to squeeze it into my schedule this week. Please do keep us in the loop re your progress, eg if you're trying the implementation described by @hhaensel

With @essenciary 's API it is quite easy to build wrappers for a new element. But in order to facilitate the usage of any quasar element I propose to introduce a general wrapper along the following lines:
```
## raw quasar elements

import Genie.Renderer.Html: HTMLString, normal_element
const NO_WRAPPER = f->f()

Genie.Renderer.Html.register_normal_element("q__raw", context = @__MODULE__)

function quasar(elem::Symbol, args...;
                wrap::Function = StippleUI.DEFAULT_WRAPPER,
                kwargs...) where {T<:Stipple.ReactiveModel}
  wrap() do
    q__raw(args...;
            StippleUI.API.attributes(
              [kwargs...],
              StippleUI.API.ATTRIBUTES_MAPPINGS
            )...)
  end |> x->replace(x, "q-raw"=>"q-$elem")
end
```
An image as in @touchft 's requirement would then be implemented by
```
quasar(:img, [], "spinner-color=\"white\""; src=:imageurl, style="height: 140px; max-width: 150px", wrap=NO_WRAPPER)
```
Note that the  `spinner-color` argument needs to go with the arguments, as hyphens are not allowed in keyword arguments.
Alternatively one could splat a `Dict` (in this case the semicolon somewhere before the Dict is mandatory!):
```
quasar(:img; src=:imageurl, style="height: 140px; max-width: 150px", Dict(Symbol("spinner-color")=>"white")..., wrap=NO_WRAPPER)
```

In the past I recommended to include a replacement rule "_"=>"-" in `StippleUI.API.attributes()` as underscores are typically not used in JS and certainly not in the quasar framework. Then you could write
```
quasar(:img, src=:imageurl, style="height: 140px; max-width: 150px", spinner_color="white", wrap=NO_WRAPPER)
```

Finally, we could also go with
```
function quasar(elem::Symbol, args...;
                wrap::Function = StippleUI.DEFAULT_WRAPPER,
                kwargs...) where {T<:Stipple.ReactiveModel}
  wrap() do
    q__raw(args...;
            StippleUI.API.attributes(
              [Symbol(replace("$k", "_"=>"-")) => v for (k,v) in kwargs],
              StippleUI.API.ATTRIBUTES_MAPPINGS
            )...)
  end |> x->replace(x, "q-raw"=>"q-$elem")
end
```
which incorporates the replacement rule only for raw quasar elements, which I personally would favour, if we don't go for a general replacement rule.

I would happily submit a PR to include this code in `StippleUI.API` if this is ok for @essenciary

**Comment by touchft** [comment]
I learned API a bit of time. Now I can wrap <q-img>, but I still have no idea how to work on html canvas.   I think dynamically updating image data (drawImage) on canvas should be more efficient than updating image through url. Correct me if I am wrong.

**Comment by touchft** [comment]
> Looking at the Dash demo, would you show the images instead of the youtube video?

I processed a series of image (frame by frame from video) and than dynamically show the image. And I made it work! Thank you!

**Comment by hhaensel** [comment]
That's great! 🚀 

Did you use the canvas now?
Would you mind to extract an example and place it on the [demo site](https://github.com/GenieFramework/StippleDemos)?

**Comment by yakir12** [comment]
I too need to dynamically show frames from a video. Having a minimal example would be very helpful indeed!

**Comment by touchft** [comment]
> That's great! 
> 
> Did you use the canvas now?
> Would you mind to extract an example and place it on the [demo site](https://github.com/GenieFramework/StippleDemos)?

I use html style "<img src=“data:image/png;base64,xxxx"/>

**Comment by hhaensel** [comment]
Well, then you could also use a "q-image" instead of a regular image, see the [WebCam Demo](https://github.com/GenieFramework/StippleDemos/blob/master/WebCam.jl) for setting this up.
If your question is answered with this, we could close this issue. But we could also leave it open, if you think we should support a js canvas in the future.

**Comment by touchft** [comment]
> Well, then you could also use a "q-image" instead of a regular image, see the [WebCam Demo](https://github.com/GenieFramework/StippleDemos/blob/master/WebCam.jl) for setting this up.
> If your question is answered with this, we could close this issue. But we could also leave it open, if you think we should support a js canvas in the future.

Great example. I feel I will get something that I want from it ! THX!
