### ISSUE TITLE
client_data bug

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/Stipple.jl#204]
client_data is  not working with new macro @vars and should use @reactive

**Comment by hhaensel** [comment]
Please be more precise in what is not working for you and paste the code and the error message.
Did you copy the code from the doc string?
I just tested that the following code works:
```julia
julia> @vars Example begin end
Example

julia> Stipple.client_data(::Example) = Stipple.client_data(r = 13)

julia> render(Example())[:data]
Dict{String, Any} with 3 entries:
  "isready"      => false
  "isprocessing" => false
  "r"            => 13
```

**Comment by hhaensel** [comment]
I did and it works, maybe you used `@vars` in the wrong way. the correct way is
```julia
@vars FormComponent begin
  name::R{String} = ""
  age::R{Int} = 0
  objects::R{Vector} = ["Dog", "Cat", "Beer"]
  warin::R{Bool} = true
end
```
You need to restart Julia after having defined FormComponent with `@reactive` because `@vars` will try to redefine the type `FormComponent` which is not allowed.

Finally, a rather general remark. We're happy to take care about issues and shortcomings of our packages. We are also happy to help here and there if things are not well documented. However, github is not a help forum. For that we have a discourse channel.
If you think that there is some issue of general interest, please post it here and try to 
- paste the code that fails, be as short as possible
- be specific about the error that occurs ("doesn't work" is rather unspecific), better paste the error message or the html output of the page or a screenshot.
That way we can quickly help and don't have to guess what's going wrong.

**Comment by alerem18** [comment]
i've tried with @vars for the first time and didn't use @reactive at all so there is no redefining anyway
