### ISSUE TITLE
Review the data sync workflow (client and server) to handle sync issues

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Stipple.jl#52]
Catch socket disconnected exceptions in JS and attempt to reconnect (or suggest full page reload if not possible).

**Comment by LMW38** [comment]
Maybe this is of any help. 

With our App we lost connection at times and we did not understand the root cause. I think our App is a normal use case for Julia: computation intensive simulations so the server has to wait until these finish. 

Observations:
- With localhost server on Windows, I noticed the connection was not (actually never) lost when I print to REPL in the computation loop. 
- When I run the Stipple App from a Docker container in Linux, the container crashes after a certain number of simulations. Doubling the memory postponed the crash. Adding "flush(stdout)" to the computation loop reduced the frequency of crashes.

The amount of memory in use ("varinfo()") varied between 160 MiB to over 1 GiB between simulations and depending on simulation parameters. Maybe it takes a certain amount of time before Julia garbage collection starts during a new simulation with different memory requirements. In Linux, with limited memory, it was fatal though.

As a counter measure, I reduced the data that I keep after a simulation and still flush in the computation loop. Now, the crashes are gone. So, if a websocket fails, it is a good idea to check memory usage and find out if a reduction helps.
