### ISSUE TITLE
how can I get something like '<div :class="hidden"></div>' ?

### ISSUE THREAD

**Issue by touchft** [GenieFramework/Stipple.jl#54]
How do I code from `Stipple.Html.div()` to get something like `<div :class="hidden"></div>` ?

Thanks

**Comment by hhaensel** [comment]
```
julia> Html.div("Hello", ":class='hidden'")
"<div :class='hidden'>Hello</div>"

julia> Html.div("Hello"; R":class" => "hidden")
"<div :class=\"hidden\">Hello</div>"
```

**Comment by hhaensel** [comment]
If we would define our
```
function xelem(elem::Symbol, prefix::String, args...;
              wrap::Function = StippleUI.DEFAULT_WRAPPER,
              kwargs...) where {T<:Stipple.ReactiveModel}
  wrap() do
    q__elem(isempty(prefix) ? elem : Symbol("$prefix-$elem"), args...; attributes([collect(kwargs)...], ATTRIBUTES_MAPPINGS)...)
  end
end
```
Then we could also do
```
mydiv(args...; kwargs...) = StippleUI.API.xelem(:div, "", args..., kwargs...)
mydiv("Hello", class = :hidden)
```
I think, I will do that change ... @essenciary what do you think?

**Comment by hhaensel** [comment]
and for the easeof use
```
xelem_pure(elem::Symbol, prefix::String, args...; kwargs...) = xelem(elem, prefix, args...; wrap = StippleUI.NO_WRAPPER, kwargs...)
```
we could even export `xelem()` and `xelem_pure()`

**Comment by essenciary** [comment]
@hhaensel Thank you

How would it work in practice? Would the users have to define their own specialized versions of `div` `span` `p` etc to support this? 

Tbh I prefer the simpler version that already works (passing the string argument). And I'm not a fan of swapping the `:` from the value to the key (eg `foo = :bar` resulting in `:foo = bar`) - I can see the appeal but to me it's confusing, feels like a case where it's hard for the users to predict the outcome (principle of least surprise) or can lead to weird bugs (eg accidentally passing a symbol instead of a string for the value).

**Comment by essenciary** [comment]
@hhaensel 
1. this has been the convention in Stipple from the beginning and yes, it is intentional. In Stipple the convention is that a symbol value is a reference to the name of a field from the ReactiveModel. With this convention, Stipple generates Vue specific HTML attributes code. 
2. this does not work in Genie which a) predates Stipple; b) does not generate Vue specific code. 
3. there should be a well defined/supported/recommended way to do these things in Genie as well - but Genie conceptually operates at a lower level of abstraction: it is JS framework agnostic. So it should allow for the generation of any kind of code for integration with any kind of framework, not just with Vue. 
4. as explicitly supporting all the possible JS frameworks is not an option (though it could be done with individual plugins/adapters, eg GenieVue.jl, GenieReact.jl, etc but that's a different story), it's best to support none, and just provide the ability for the users to write any kind of JS framework integration code. What do I mean by that? Say we add support for Vue in Genie so that `foo = :foo` produces `:foo = "foo"`. But what if in some other framework the HTML properties should be `foo: = "foo"`? We can't optimize for Vue in Genie. 
5. I agree that the fact that Stipple elements support `foo = :foo` but Genie elements do not is super confusing and should be addressed. So yes, unified syntax would be great. 

I think a good approach could be: 
1. extend Genie to allow/provide a way to write non-standard HTML attributes (eg containing `@`, `:`, `-`, etc) but do not explicitly support any specific JS framework. I expect this will be non-breaking as the most straightforward way would be by using `":foo = 'foo'"` which already works. So it's mostly a documentation issue. 
2. if Stipple is used, from Stipple itself, specialize the `Renderer.Html` elements API to be compatible with the Stipple API so that all the elements work the same way. 

Makes sense?

**Comment by essenciary** [comment]
Actually on more thought, `GenieVue.jl` might be the best approach. It can be a separate plugin that extends the Genie API with Vue support - and can be used by Genie users to build Vue apps without Stipple. And Stipple would use it as a dependency. 
Thoughts? 

This also sets up the foundation for other `GenieReact.jl` `GenieAngular.jl` and others. 

Thoughts?

**Comment by hhaensel** [comment]
@essenciary I think we have addressed all of the issues and we can close this...

**Comment by essenciary** [comment]
Yup!
