### ISSUE TITLE
Remove `Stipple.init(m::M, ...)` and document workflow (`isready` and other app events)

### ISSUE THREAD

**Issue by mdotend** [GenieFramework/Stipple.jl#97]
Hi again :)
I just noticed this strange behaviour when initializing a ReactiveModel. 
When I call the init()-Function before altering values in the Struct, the values are visible on the backend side but they are not transferred to the remote Endpoint and are thus stuck on the default values. But if I first create the Struct and set the values and afterwards call the init()-Function, the values are overwritten again and the default values are in place (I have found both ways in the demos).

## Expected Behaviour
Initialize a model with Stipple.init() -> change values in the back end -> see changes in the front end

## Code Example
```
using Genie, Stipple, StippleUI

@reactive mutable struct Test <: ReactiveModel
    changed::R{Bool} = false
end

function changeModel(pModel)
    pModel.changed[] = true
    return pModel
end

function initFirst()
    model = Stipple.init(Test())
    return changeModel(model)
end

function initLast()
    model = changeModel(Test())
    return Stipple.init(model)
end


a = initFirst()
b = initLast()

println(a.changed[])
println(b.changed[])



function ui(model)
    page(model, class = "container", [
        p(
            span("", @text(:changed))
        )
    ]) |> html
end

route("/a") do 
    ui(a)
end
route("/b") do 
    ui(b) 
end 

up(8020, open_browser=true)
```

Am I missing something here or approaching this from the wrong angle?

**Comment by essenciary** [comment]
@mdotend That is by design - there are 2 `Stipple.init` methods: 
* `init(::Type{T}, ...)`
* `init(T, ...)`

The first one is valid, initializing using the Type -- which clearly expresses the idea that there is no state, `init` is set up with the default values and all updates are to be sent when the `isready` handler is triggered. 

The `init(T, ...)` has been kept for legacy and it actually calls `init(typeof(T))` -- but indeed, it's misleading. We'll remove it. 

Is it clear how `init` should be used and when the updates should be sent? 

I'll add this to the docs ASAP.

**Comment by hhaensel** [comment]
The syntax has changed already quite some time ago. The new syntax is `init(Test)` and always initializes a model with the default values.
In order to have an up to date model you should include a handler that pushes the actual values of the model to the backend.
```julia
on(model.isready) do isready
    isready || return
    push!(model)
end
```
(Currently on my mobile, so no guarantee for typo-free code 😉 )

**Comment by mdotend** [comment]
Thank you for the explanations!
I guess, that I understood the init function now, but still have my issues with the isready handler. I have only found one example in the demo, but this also uses sessions, which is a problem for another time :D

The handler @hhaensel posted works fine for a simple example, but it does not work for me with dynamic content. As far as I understand, the page has to be loaded for the value of model.isready to be set true. But when I want to generate content based on the values in the model, I get lost again.
Would a workflow look like this ? : init model -> add handler -> load page -> push!(model) when isready to sync -> change values in the model -> generate html content

And as far as I tested, the isready state is only set true on the first load of the page, and e.g. not affected by reloading the page, which might be an issue later on.

**Comment by essenciary** [comment]
Yes, this is for a post I've been wanting to write for a long time, about the life-cycle and the various events of an app. Let me see if I can explain the gist here. So there are quite a few layers with various types of interactions. 

1/ Sync request -- server side response
-> browser makes request to a URL
-> the request is handled by the corresponding `route`
-> the initial response/payload is prepared, meaning composing the HTML page and injecting all the JS scripts/files 
-> at this step we create a new instance of the model, we attach the handlers, and we call `Stipple.init(ModelType)` (because effectively the result of `Stipple.init` is a JS file which contains the JS version of our model)
-> at this point the developer can customise the HTML response by adding all sorts of conditional logic as needed
-> the JS version of the model generated by `Stipple.init` is based on the Model Type and not on an instance because JS assets are designed to be cached and served off a CDN, so we do not want the JS Model file to be customised -- it always reflects the default state of the model and it's the same for all the users. 
=> when all this is done, the resulting HTML response is sent to the browser

2/ Client side rendering
-> the browser receives the HTML response (which can be customised for each user) and renders it
-> the browser loads all the JS files bundled with the initial response

3/ JS execution -- client side
-> as the browser renders the page the JS included with the response is executed
-> Vue.js is loaded and the data passed in the JS Model is applied to the HTML of the page (ex all the bindings like `@text`, `@bind`; logic like `@iif`, `@recur`, etc)
-> a connection back to the server is established (over WebSockets if available or using Ajax push/pull if WebSockets are not available)
-> when the connection is successfully established the `isready` event is triggered, causing the `isready` property of the Julia model to be switched to `true`

4/ Async requests -- server side responses
-> as data is exchanged over the async connection with the frontend, various properties of the Julia model are changed, causing their handlers to be triggered
-> the developer implements the logic around these change handlers
-> at this point we can no longer send HTML payloads (cause that was part of the initial HTML response at 1) - we can only update properties of the model which are pushed to the frontend causing the UI to update to reflect these changes. 
-> however, this is not necessarily a limitation as we can bind the HTML content of an element to be dynamic and we can update it -- or even we can send a JS payload to be executed on the frontend (so we can effectively inject JS scripts into the page). Thinking about it, we could maybe add some dedicated APIs to make updating the HTML of an element easier (by providing a higher level wrapper around these techniques). 

---

Does this make sense? Looking forward to your feedback as this can become the doc page I wanted to write :)

**Comment by mdotend** [comment]
Yes this does make sense and is a good description, though I am still struggeling to convey it to my problem at hand.
I understood that the logic has to be already in the html, so I used @recur, which worked out quite well. 
I still have issues with accessing the v-for variable for my checkboxes, but I guess, that this is just an framing issue.

My biggest problem at the moment is, that the synchronization only happens on the first time the server is called, after a reload or in a new page the model won't get updated. Do I have to reset the front end model or force a rewrite?

And are the macros for the vue elemts only defined in the Elements.jl or is there another file as well?

The reload probem can be replicated with this small script:
```
using Stipple, StippleUI

@reactive mutable struct Test <: ReactiveModel
    changed::R{Bool} = false
    sweetVec::R{Vector} = []
end

function changeModel!(pModel)
    pModel.changed[] = true
    pModel.sweetVec[] = ["abc","def"]
end

function initWithHandler()
    model = init(Test)
    on(model.isready) do isready
        isready || return
        push!(model)
        changeModel!(model)
    end

    return model
end

c = initWithHandler()

println(c.changed[])

function ui(model::Test)

    page(model, class = "container", [
        p(
            span("", @text(:changed))
        )
        p(" {{vec}} ", @recur(:"vec in sweetVec"))
    ], @iif(:isready)) |> html
end

route("/") do 
    ui(c) 
end 
up(8020, open_browser=true)
```

**Comment by hhaensel** [comment]
Hi @mdotend ,
there is one point that we didn't see up to now. The fact that it doesn't update correctly has to do with timing. I worked around it with a delayed `@async` call. (@essenciary that should be either solved or included in our docs ...)

Here's a fully working script
```julia
using Stipple, StippleUI

@reactive! mutable struct Test <: ReactiveModel
    changed::R{Bool} = false
    sweetVec::R{Vector} = []
end

function changeModel!(model)
    model.changed[] = true
    model.sweetVec[] = ["ab", "cd", "ef", "gh"]

    model
end

function handlers(model)
    on(model.isready) do isready
        isready || return
        @async begin
            sleep(0.1)
            push!(model)
        end
    end

    model
end

model = init(Test, debounce = 0) |> handlers |> changeModel!

function ui(model::Test)
    page(model, class = "container", row(cell(class = "st-module", [
        toggle("Changed", :changed)
        list("", :bordered, :separator, style = "max-width: 25vw",
            [item("Hello {{ sweetVec[$(i-1)] }} ", :clickable, :v__ripple) for i in 1:length(model.sweetVec[])]
        )
        separator()
        list("", :bordered, :separator, style = "max-width: 25vw",
            [item("World {{ vec }}", @recur("vec in sweetVec"), :clickable, :v__ripple)]
        )
    ])), @iif(:isready)) |> html
end

route("/") do 
    global model
    ui(model)
end

up(8020, open_browser=true)
```
![grafik](https://user-images.githubusercontent.com/31985040/158479641-914cfd04-a48b-491e-95c2-cee2dbb884e5.png)

**Comment by hhaensel** [comment]
@essenciary We could hide the `on(model.isready)` handler in the init routine, what do you think?

**Comment by hhaensel** [comment]
I'd add a kwarg "push_on_isready = true"

**Comment by essenciary** [comment]
Yes, we could put it on init, makes sense.

**Comment by essenciary** [comment]
I can work on it - I'm struggling to make the session ModelStorage work, for some reason the session state gets pushed to all channels/clients.

**Comment by hhaensel** [comment]
I saw that sometimes the model wouldn't update after redefining `ui(model::Test)`. I couldn't get a clue and will do some more testing...

**Comment by mdotend** [comment]
@hhaensel Unfortunately I could not get your script working, I experience the same behaviour as before. Is there anything I can do to assist you?

**Comment by hhaensel** [comment]
It's strange, but today it doesn't work for me either. I did update all my packages lately. After increasing the sleep value from 0.1 to 0.5, it worked again.
@essenciary We might have to implement a handshake here...

**Comment by essenciary** [comment]
I'll check it out - I have multiple changes for the 0.22 upcoming release. Things work smoothly on my side, including with the Session `ModelStorage` support. 

I'll run this example on the new codebase.

**Comment by essenciary** [comment]
Indeed, it wasn't working in some situations. The problem was that the frontend would successfully subscribe to the websockets connection and immediately trigger the `isready` event. However, on the first run (and even on subsequent runs sometimes), even though the websockets connection was ok, the backend wasn't ready (meaning fully configured to handle model updates). So effectively the frontend would send the `isready` event, the backend handlers would be triggered, but the backend would fail to push the updated model to propagate changes back to the frontend. However, the `isready` event would be consumed. 

Initially we solved this by adding the delay to allow the backend to be ready. In this case, an even larger delay was needed. However, I never really liked the delay approach. It was just a random number that in some case would delay the rendering, or in others would be too short and not help, like in this case. 

So I have now completely refactored it to be event driven: the `isready` event waits until the subscription is complete, including the full backend. This also allowed us to cleanup and simplify our code by removing the delay logic. Seems to work great. Will require v0.22 (currently on master). 

I have not added the automatic push of the model on `isready` as I'm not sure it's a good idea. I expect that in many cases the users will want to write their own (more complex) logic to execute on `isready`. While in others, they will not want/need to push anything.

**Comment by hhaensel** [comment]
Wow, I'll check this out! 🚀
